### ISSUE TITLE
About the version 

### ISSUE THREAD

**Issue by zhuzhuxue** [mcvarer/HSI-VAE-Classification#1]
Dear Sir, I am a junior learner of hyperspectral classification, and I am honored to be able to learn from your code about VAE. Regarding your code, I have a question, please give me some pointers,  Sincerely！！！ 
I want to know the version of your project.The versions about your **tensorflow, keras, cuda and cudnn.** Because I always get the wrong version error when debugging the program, thank you!

**Comment by mcvarer** [comment]
hi, i will send you the requirements file when available. New changes have
been made to the code. Those on GitHub are old so they may not work.

12 Tem 2020 Paz 10:55 tarihinde zhuzhuxue <notifications@github.com> şunu
yazdı:

**Comment by zhuzhuxue** [comment]
Thanks！I don't know how to contact you will be more conveniently, soI will leave my email here: 15166006440@163.com. 
Futher more ,My English grammar is not very well, I just want to express my deep gratitude to you, if there are any misunderstandings, please forgive me.
I will look forward to your reply and always pay attention to the email. Expressing my sincere thanks here!!!

**Comment by mcvarer** [comment]
Could you share linkedin profile according to my criteria I don't share private code. I'm also writing article this project. Therefore I can share it when my article is finished.

**Comment by zhuzhuxue** [comment]
Okay sir, I finished my profile. I am a college student and I am learning hyperspectral classification by myself now.
First of all, I must assure you that I will not steal your results for my own forever. I just want to run successfully the code which you share on github. Because I was always reported some error. 
I apologize to you again for your inconvenience. I hope you can give me some pointers, such as how to configure the environment to successfully run the code. Thank you!
